bbands:
  ind: BBANDS
  col: close_price
  timeperiod: 12
  nbdevup: 1
  nbdevdn: 1
  matype: 0
  ret: [upper, middle, lower]

logic:
  buy: bbands.upper > 10 and bbands.lower < 20
  sell: bbands.upper < 15 and bbands.lower > 50
