broker: binance
symbol: btcusdt
interval: 15m
market: futures
strategy: sma_strategy.json
start: 2021-11-10 17:55:00    # ISO 8601

# columns must include TOHLCV data
# required columns: open_time, open_price, high_price, low_price, close_price, volume
columns: [open_time, open_price, high_price, low_price, close_price, volume, number_of_trades]
socket_url: wss://stream.binance.com:9443/ws/
socket_type: kline
